fix : 해당 사용자의 모든 이미지가 삭제되던 오류 수정
NBC-Spring6-Final-Team15/sprout-market pull request #102
Opened 2024-11-08 07:18 UTC by asitwas729

- [x] 해당 사용자의 모든 이미지가 삭제되던 오류 수정

2024-11-08 07:25 UTC, kikye04040 requested changes
aplication.properties 여기서 API 키는 민감한 정보는 local에서 쓰도록 변경해주실 수 있나용??!

2024-11-08 07:30 UTC, durururuk requested changes
대박,,,수고하셨습니다

2024-11-08 07:30 UTC, durururuk commented on src/main/resources/application.properties
> +api.key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
이거...노출돼도 괜찮으신가요?

2024-11-08 07:37 UTC, kikye04040 commented on src/main/resources/application.properties
> +api.key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
제 말도 이 의미였습니다..!! 이것만 숨겨주시면 될 거 가타요~~

2024-11-08 07:38 UTC, asitwas729 commented on src/main/resources/application.properties
> +api.key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
숨겼습니다!

2024-11-08 07:40 UTC, kikye04040 approved these changes
수고많으셨습니다!

2024-11-08 07:56 UTC, jitaeklee approved these changes

2024-11-11 01:03 UTC, durururuk approved these changes

2024-11-11 01:05 UTC, merged