Item controller에 모든 기능 테스트 코드 작성 완료
NBC-Spring6-Final-Team15/sprout-market pull request #42
Opened 2024-10-25 13:39 UTC by asitwas729

- [x] item controller API 주소 변경(동사형->명사형)
- [x] service단에 public으로 만들었던 코드 다시 repository로 이동
- [x] 승재님이 만드신 매물 내용수정 테스트 코드 삭제(사유: 오류)

테스트 코드
- [x] 매물 등록 성공
- [x] 매물 판매상태 변경 성공
- [x] 사용자, 자신의 매물 (논리적)삭제 성공
- [x] 관리자, 신고된 매물 (논리적)삭제 성공
- [x] 사용자, 자신의 모든 매물 조회 성공
- [x] 매물 단건 상세 조회 성공
- [x] 사용자 반경 5km안에 있는 특정 카테고리에 속하는 매물 조회 성공

2024-10-26 12:44 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/item/controller/ItemController.java
오 단순 URI만 바꾼 게 아니라 jpa에서 사용하는 이름과 다르게 설정하셨군요 제가 맡은 부분도 체킹해봐야겠네요

2024-10-26 12:46 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/item/repository/ItemRepository.java
> +    default Item findByIdOrElseThrow(Long id) {
이것도 바로 적용해주셨네요 좋습니다!!!!!!!

2024-10-26 12:51 UTC, durururuk requested changes

2024-10-26 12:51 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/item/repository/ItemRepository.java
오 바로 default 메서드로 신철호 튜터님이 해주신 피드백 적용해주셨군요!!
그런데 매물도 논리삭제다보니 조회할 때 AND i.status = 'ACTIVE' 같은 조건절이 하나 더 있어야 할 것 같습니다!

2024-10-26 12:51 UTC, durururuk commented on src/test/java/com/sprarta/sproutmarket/domain/item/controller/ItemControllerTest.java
와,,,,,고생하셨습니다

2024-10-26 13:38 UTC, kikye04040 approved these changes
확인했습니다!!! 수고 많으셨습니다!!!!!!!!!!

2024-10-27 07:40 UTC, asitwas729 commented on src/main/java/com/sprarta/sproutmarket/domain/item/repository/ItemRepository.java
넵 다음커밋에 조회관련 기능들에 모두 올려두겠습니다!

2024-10-27 07:46 UTC, asitwas729 commented on src/test/java/com/sprarta/sproutmarket/domain/item/controller/ItemControllerTest.java
어머 제가 controller url이랑 mapping타입 변경하면서 오류였던것 같습니다. 
ㅋ 쓸데없이 두번 일 했네요ㅜㅜ

2024-10-27 10:27 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/item/repository/ItemRepository.java
넵! 고생하셨습니다!

2024-10-27 10:28 UTC, durururuk commented on src/test/java/com/sprarta/sproutmarket/domain/item/controller/ItemControllerTest.java
아하... 세상에 ㅋㅋㅋㅋ ㅠㅠ..

2024-10-27 10:28 UTC, durururuk approved these changes

2024-10-27 10:29 UTC, merged