Feat/review jitaek
NBC-Spring6-Final-Team15/sprout-market pull request #43
Opened 2024-10-27 08:52 UTC by jitaeklee

- [x] 거래 예약, 완료 구현
- [x] 거래 컨트롤러 테스트 구현

2024-10-27 10:39 UTC, durururuk requested changes
일요일인데도 작업 수고하셨습니다!

2024-10-27 10:39 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/trade/entity/Trade.java
>      @JoinColumn(name = "item_id")
이 부분 @ManyToOne 어노테이션 누락된 것 같습니다!

2024-10-27 10:39 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/trade/service/TradeService.java
예약 상태 바꿀 때 판매 상태까지 신경쓰신 부분 좋습니다!

2024-10-27 10:39 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/common/enums/ErrorStatus.java
> +    CONFLICT_TRADE(HttpStatus.CONFLICT, 400, "이미 물건이 거래됐습니다."),
이 부분 앞에 BAD_REQUEST_CONFLICT_TRADE 같은 걸로 바꿔주시면 감사하겠습니다!

2024-10-27 11:06 UTC, jitaeklee commented on src/main/java/com/sprarta/sproutmarket/domain/trade/entity/Trade.java
>      @JoinColumn(name = "item_id")
어? 파란색 누르니까 보이는데요?

2024-10-27 12:18 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/trade/entity/Trade.java
>      @JoinColumn(name = "item_id")
앗 그러네요 죄송합니다

2024-10-27 12:19 UTC, durururuk approved these changes

2024-10-28 01:13 UTC, kikye04040 approved these changes
확인했습니다!

2024-10-28 01:13 UTC, merged