이미지 구조 변경, 오류 수정
NBC-Spring6-Final-Team15/sprout-market pull request #81
Opened 2024-11-01 05:47 UTC by asitwas729

- [x] Image -> ItemImage, S3Image, ProfileImage로 분리
- [x] param 오류 해결
itemService 리팩토링
- [x] @NoArgsConstructor(access = AccessLevel.PROTECTED)로 변경
- [x] S3ImageService 용량제한(5MB)
- [x] Item Entity @builder패턴에서 생성자로 변경
- [x] Item DTO 일부 제외하고 전부 빌더 패턴으로 변경

Image 등록하는 방법
1. ("/s3/upload") 로 이미지 S3에 저장하기
2. 그 후 ItemImage 또는 ProfileImage에서 이미지 DB에 저장하기

2024-11-01 11:03 UTC, durururuk commented on HELP.md
이건 이름 전체 변환 하다가 바뀐 건가요 ㅋㅋㅋㅋㅋ

2024-11-01 11:12 UTC, durururuk requested changes

2024-11-01 11:12 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/category/repository/CategoryRepository.java
이건 기본 쿼리메서드에서 동작 안 해서 추가한 JPQL인가요..?

2024-11-01 11:12 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/item/controller/ItemController.java
> +        return ResponseEntity.ok(ApiResponse.onSuccess(itemResponse));
여기,,,는 ok로 바꾸신 이유가 따로 있으신가요?

2024-11-01 11:15 UTC, jitaeklee approved these changes
확인했습니다

2024-11-01 11:19 UTC, asitwas729 commented on HELP.md
ㅋㅋㅋㅋ 그러네용 왜그런가했더니ㅋㅋㅋ

2024-11-01 11:21 UTC, asitwas729 commented on src/main/java/com/sprarta/sproutmarket/domain/item/controller/ItemController.java
> +        return ResponseEntity.ok(ApiResponse.onSuccess(itemResponse));
어..., 이거 바꾸면 안되는거였나용....?

2024-11-01 11:22 UTC, asitwas729 commented on src/main/java/com/sprarta/sproutmarket/domain/category/repository/CategoryRepository.java
네에 근데 저거 바꿨을때는 해결 못했는데 지금은 돼용

2024-11-01 11:33 UTC, durururuk commented on src/main/java/com/sprarta/sproutmarket/domain/item/controller/ItemController.java
> +        return ResponseEntity.ok(ApiResponse.onSuccess(itemResponse));
리소스 자원 추가라서 201로 작성돼있었습니다!

2024-11-04 01:31 UTC, durururuk approved these changes

2024-11-04 01:48 UTC, merged